clip: 0.2
exp_id: v02_simple_env_60_reward_proportion
gamma: 0.99
log_dir: summary/v02_simple_env_60_reward_proportion
lr: 0.0003
max_timesteps_per_episode: 800
n_updates_per_iteration: 50
render: true
render_every_i: 10
save_freq: 2
seed: null
timesteps_per_batch: 8000
